pipeline:
  create_cluster:
    image: banzaicloud/plugin-pipeline-client:latest
    pull: true

    cluster_name: "sebascicd1"
    cluster_provider: "azure"
    cluster_location: "eastus"
    azure_resource_group: "sebastian_eastus"
    azure_node_count: 2
    node_instance_type: "Standard_B4ms"

    secrets: [plugin_endpoint, plugin_token]

  install_monitoring:
    image: banzaicloud/plugin-pipeline-client:latest
    deployment_name: "banzaicloud-stable/pipeline-cluster-monitor"
    deployment_release_name: "monitor"

    secrets: [plugin_endpoint, plugin_token]

  install_zeppelin:
    image: banzaicloud/plugin-pipeline-client:latest
    deployment_name: "banzaicloud-stable/zeppelin-spark"
    deployment_release_name: "release-1"
    deployment_state: "created"
    deployment_values:
      zeppelin:
        sparkSubmitOptions:
          eventLogDirectory: "wasb://spark@{{ .AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net/"
          azureStorageAccountName: "{{ .AZURE_STORAGE_ACCOUNT }}"
          azureStorageAccessKey: "{{ .AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}"
      historyServer:
        enabled: true
      spark:
        spark-hs:
          app:
            logDirectory: "wasb://spark@{{ .AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net/"
            azureStorageAccountName: "{{ .AZURE_STORAGE_ACCOUNT }}"
            azureStorageAccessKey: "{{ .AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}"

    secrets: [plugin_endpoint, plugin_token, azure_storage_account, azure_storage_account_access_key]

    remote_checkout:
      image: banzaicloud/drone-plugin-k8s-client:latest
      original_image: plugins/git

    run:
      image: banzaicloud/drone-plugin-k8s-client:latest
      original_image: banzaicloud/zeppelin-client:latest
      notebook_name: "sf-police-incidents"
      notebook_file_path: "sf-police-incidents-azure.json"
      notebook_state: "running"
      zeppelin_endpoint: "http://release-1-zeppelin:8080/zeppelin"
